### ISSUE TITLE
Issue calculating Buckaroo fee on credit memos

### ISSUE THREAD

**Issue by stefanfr** [tig-nl/buckaroo-magento1#13]
When creating a credit via API the module calculates fee tax based on the order values. The problem is that this results in a NaN:

`$totalBaseFee = $order->getBaseBuckarooFee();`
`$ratio        = $baseFee / $totalBaseFee;`

Both `$baseFee` and `$totalBaseFee` are 0 in this case resulting in a `$ratio = NaN` further calculations will be based on NaN ending with a grand total of NaN

---

- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If your issue contains security sensitive information
- [ x ] This issue does not contain any security sensitive information

**Comment by tig-jaspersmits** [comment]
Hi @stefanfr ,

Thanks for contacting us about the problem you are running into. Are you doing the refund from the Buckaroo Plaza or from Magento itself? Or doesn't it matter? And I need to keep the fee empty when setting it up?

Is it possible to share tax settings and Buckaroo settings regarding the fee etc? Because I need to test it with identical settings to yours.

Kind regards,

Jasper

**Comment by stefanfr** [comment]
Hi @tig-jaspersmits,

Thanks for your response.

In our case we create the credit via SOAP with `salesOrderCreditmemoCreate`.
https://devdocs.magento.com/guides/m1x/api/soap/sales/salesOrderCreditMemo/sales_order_creditmemo.create.html
The order was paid with ideal (no fee)
![image](https://user-images.githubusercontent.com/7378394/64232434-3d750f00-cef2-11e9-8d12-6b9ae929ecec.png)
And the buckaroo fee is set to (0):
![image](https://user-images.githubusercontent.com/7378394/64232924-3dc1da00-cef3-11e9-94b5-9ad85bd70e58.png)

When I debug `app/code/community/TIG/Buckaroo3Extended/Model/PaymentFee/Order/Creditmemo/Total/FeeTax.php`
I see that the $fee and $baseFee are set to:
`$fee     = 0.0000;
$baseFee = 0.0000;`

Resulting a **true** in the next if statement `if ($fee && $baseFee)` this should be **false** as there is no Tax to calculate.

I hope this will help solving the issue
Thanks,
Stefan

**Comment by tig-jaspersmits** [comment]
Hi @stefanfr ,

Thanks for your response. I'll discuss and test it. Once I have more information I'll get back to you.

Kind regards,

Jasper

**Comment by tig-jaspersmits** [comment]
Hi @stefanfr ,

I just placed this on our backlog. We will look for a solution and patch it in the extension once we release a new version.

Kind regards,

Jasper

**Comment by tig-jaspersmits** [comment]
Because of a clean-up action we will close this ticket. The ticket has been on our backlog and is still open. This indicates that we will work on it in the future or once Buckaroo decides to give priority to this compatibility.
