### ISSUE TITLE
Please update the module

### ISSUE THREAD

**Issue by diedburn** [tig-nl/buckaroo-magento1#8]
### Make sure you are using the *latest* version: https://tig.nl/buckaroo-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Buckaroo Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with the TIG Buckaroo Magento extension)
- [ ] Site support request (request for adding support for a new site)
- [x] Feature request (request for a new functionality)
- [x] Question
- [x] Other

---

Please update the module to the latest version 4.18.0

**Comment by tig-robertgrundeken** [comment]
Hi @diedburn,

Thanks for noticing!

The policy agreed on with Buckaroo is to give all the merchants 2 weeks to update their shop with this version. After that period the release will be public. 

I'll hope you understand.

Robert

**Comment by diedburn** [comment]
That explains everything.

Sorry for the inconvenience!
